### ISSUE TITLE
Lack of Thumbstick Deadzones in WMR OpenXR, lack of proper WMR Controller bindings

### ISSUE THREAD

**Issue by Maloonkey** [DaXcess/LCVR#39]
Running the mod natively in a Mixed Reality environment (No SteamVR input) causes sliding movements due to the thumbstick values not being exactly 0.

The game is also unplayable in LCVR with the [Samsung Odyssey controllers](https://p.turbosquid.com/ts-thumb/fF/1x3i0z/Lo3LQ7QY/samsung_hmd_odyssey_controller_01/jpg/1507308127/1920x1080/fit_q87/e6a6806ff8cf6477256448d278ab6fad432844f2/samsung_hmd_odyssey_controller_01.jpg) because of improper and missing bindings, seems to be because nearly half of the WMR inputs under UnityXR are unique or not lining up properly with the UnityXR input nodes used by LCVR.

There aren't anything like A or B buttons on these controllers, so discarding, jumping, recalibration, and possibly a few more are impossible as they aren't bound to anything the controllers can do.

If running the mod in SteamVR, the crouch and sprint bindings become unusable because of SteamVR taking up the thumbstick presses to display the SteamVR UI (even disabling this part of SteamVR just makes the thumbstick presses do nothing, but this is a problem of SteamVR)

**Comment by DaXcess** [comment]
Unfortunately since I do not own any other controllers besides Quest 2 controllers, it is really difficult for me to implement "different type" controllers (no ABXY, trackpads, etc), since I wouldn't know what "normal" binds are for these type of controllers (sprint, jump, interact, etc). This mod supports overriding the default input bindings, but this is still missing documentation on how/where to do it.

If the inputs require "double bindings" on these controllers (so having to press two buttons for one action) then that is not yet supported in the mod.

One thing that will definitely happen is that *somewhere* a list of official binding overrides will be placed for the people who use different type of controllers.

**Comment by Maloonkey** [comment]
Ah, that's alright, I totally understand. I mean WMR itself is having support dropped by Microsoft now so these controllers are now a niche of a niche.

Most games and mods I've seen that support this type of controller usually treat the trackpad as a DPAD, which isn't optimal but is better than having no buttons at all. The Menu button between the stick and trackpad is also unused often despite being the only proper button on these things.

**Comment by DaXcess** [comment]
WMR bindings are being added via the [LCVR Controller Profiles](https://github.com/DaXcess/LCVR-Controller-Profiles) repo.
