### ISSUE TITLE
Keybinds do not work for Cosmos Elite.  

### ISSUE THREAD

**Issue by xlukewarmx** [DaXcess/LCVR#48]
My buddy is using a Cosmos Elite and is unable to jump in game.  There are also some other buggy issues with the remotes not working properly.  

Is there any fix for this? 
Thanks.

**Comment by DaXcess** [comment]
There is a special [LCVR Controller Profiles](https://github.com/DaXcess/LCVR-Controller-Profiles) page which contains a list of different input bindings for different controllers. There are no bindings for the Cosmos Elite as of yet, since these bindings can realistically only be created by people who own these controllers (I in fact do not own these controllers).
