### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by DaXcess** [DaXcess/LCVR#5]
Tracking everything that has to be done before I will publish the first release.

- [x] #4 (Checked because I think its good enough for release, but requires some QoL improvements)
- [x] #6
- [x] #9 

*List is subject to change*

Current target game version: **V49**

**Comment by Spircen** [comment]
![784478122916577301](https://github.com/DaXcess/LCVR/assets/46639834/337c5f82-342d-4821-83ea-15b92bd3802e)

Any updates on the release date?

**Comment by midblep** [comment]
![Image](https://github.com/DaXcess/LCVR/assets/26364449/16088af9-419f-4863-930b-96333207a3f2)

@Spircen fuck you

**Comment by andygun111** [comment]
@midblep bro has no chill

**Comment by FoxbitDreamtail** [comment]
So I have come to notice that steamvr on Linux is the only way to play any VR game on Linux that I know of, at least easily. Since I have to use steam VR and proton for a certain games, I have noticed that the games that run natively run much better than those that run through proton, the long and short of what I'm doing right now is asking can there please be a Linux native so that Linux users don't have to jump through hoops to try getting this working on our Linux machines, or would that require recompiling the game from scratch if so we will continue to fight against tyranny and all that b******* that most Linux users say anyway, I'm just saying that there are few VR mods that work in Linux properly, if it would be possible please make as much of it operating system independent as possible, it would make proton much less of a headache.

**Comment by DaXcess** [comment]
> So I have come to notice that steamvr on Linux is the only way to play any VR game on Linux that I know of, at least easily. Since I have to use steam VR and proton for a certain games, I have noticed that the games that run natively run much better than those that run through proton, the long and short of what I'm doing right now is asking can there please be a Linux native so that Linux users don't have to jump through hoops to try getting this working on our Linux machines, or would that require recompiling the game from scratch if so we will continue to fight against tyranny and all that b******* that most Linux users say anyway, I'm just saying that there are few VR mods that work in Linux properly, if it would be possible please make as much of it operating system independent as possible, it would make proton much less of a headache.

The game has no Linux native version so that is out of my control

**Comment by FoxbitDreamtail** [comment]
So proton is just like with beat saber unfortunately.

**Comment by JTMCDev** [comment]
No way the game that is designed for windows actually runs better on windows than through an emulator No way!11!!!!!11!1

**Comment by FemboyAzura** [comment]
what version is this compatable with rn?

**Comment by FoxbitDreamtail** [comment]
> No way the game that is designed for windows actually runs better on windows than through an emulator No way!11!!!!!11!1

Wine and Proton are not emulators, they are compatibility layers. some games even run substantially better than the same executable running in linux native!

**Comment by agmass** [comment]
> No way the game that is designed for windows actually runs better on windows than through an emulator No way!11!!!!!11!1

this man got hard ratio'd and deserved it

**Comment by DaXcess** [comment]
Released
