### ISSUE TITLE
Where is mod in thunderstore

### ISSUE THREAD

**Issue by jonafinmicclen** [DaXcess/LCVR#65]
I click on the link and nothing is there.

**Comment by Oslott1** [comment]
It's not released yet guys. It's just preparation for the release!

Just as a reminder to all of us, DaXcess is not getting paid for all this hard work being done and countless hours invested into this project, just so that the mod can be enjoyed by the lethal community! DaXcess is not being paid by the lethal company dev, not by steam, not by you, me or any of us.

We are just here to enjoy the fruits of a great dev's labour and we should all remember to appreciate. Instead of complaining, being negative, demanding answers and being impatient (not saying that's what you are by creating this issue!), we should all just be thankful we even have this mod and if you'd like to contribute, please do continue reporting bugs and submitting constructive criticism! If we didn't have this mod in the first place, there wouldn't be anything to complain about! lol.

Thank you DaXcess for being so generous in giving your time to do this for us out of the kindness of your heart. Please take all the time that you need to upload the final release!

**Comment by jonafinmicclen** [comment]
I know that I'm very thankful and would help if I knew more about this type of modding specifically. I just had seen them listed and thought they were meant to be there, my bad.

**Comment by DaXcess** [comment]
Oh yeah its so biggy, release is today and I prepared the README's for it because I would surely forget to update them after release otherwise

**Comment by DaXcess** [comment]
It's out on Thunderstore.
